PATCH http://localhost:3000/athletes/6814c6a64b65793b5fb02405 HTTP/1.1
Content-Type: application/json

{
    "name": "Carlos Alcaraz",
    "country": "Spain",
    "birthYear": 2003,
    "sportId": "680b9c504f59aa37fc651922"
}